name: Build and Test PR

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test --info

      - name: Generate Allure Reports
        run: ./gradlew allureReport

######## couldn't fix service on GIT
#      - name: Serve Allure Reports
#        run: ./gradlew allureServe

      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: build/allure-results

